# Generated by Django 2.2 on 2023-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20230409_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='busy',
            field=models.CharField(choices=[('B', 'Busy'), ('F', 'Free')], default='B', max_length=1),
        ),
    ]
