# Generated by Django 2.2 on 2021-06-27 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_flatten', '0001_initial'),
        ('booklist', '0002_auto_20210627_0913'),
        ('locations', '0001_initial'),
        ('talenttrack', '0001_initial'),
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='talenttrack.Topic', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='workcolleague',
            name='colleague_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcolleague',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='talenttrack.Designation'),
        ),
        migrations.AddField(
            model_name='workcolleague',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talenttrack.WorkExperience'),
        ),
        migrations.AddField(
            model_name='workcollaborator',
            name='collaborator_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcollaborator',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprises.Enterprise'),
        ),
        migrations.AddField(
            model_name='workcollaborator',
            name='companybranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterprises.Branch'),
        ),
        migrations.AddField(
            model_name='workcollaborator',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='talenttrack.Designation'),
        ),
        migrations.AddField(
            model_name='workcollaborator',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenttrack.WorkExperience'),
        ),
        migrations.AddField(
            model_name='workclient',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workclient',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprises.Enterprise'),
        ),
        migrations.AddField(
            model_name='workclient',
            name='companybranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterprises.Branch'),
        ),
        migrations.AddField(
            model_name='workclient',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='talenttrack.Designation'),
        ),
        migrations.AddField(
            model_name='workclient',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenttrack.WorkExperience'),
        ),
        migrations.AddField(
            model_name='topic',
            name='skills',
            field=models.ManyToManyField(to='db_flatten.SkillTag'),
        ),
        migrations.AddField(
            model_name='superior',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='talenttrack.Designation'),
        ),
        migrations.AddField(
            model_name='superior',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenttrack.WorkExperience'),
        ),
        migrations.AddField(
            model_name='superior',
            name='superior_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publications',
            name='author',
            field=models.ManyToManyField(to='booklist.Author'),
        ),
        migrations.AddField(
            model_name='publications',
            name='genre',
            field=models.ManyToManyField(to='booklist.Genre'),
        ),
        migrations.AddField(
            model_name='publications',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklist.Publisher'),
        ),
        migrations.AddField(
            model_name='publications',
            name='tag',
            field=models.ManyToManyField(to='db_flatten.SkillTag', verbose_name='Tag / Associated Skill'),
        ),
        migrations.AddField(
            model_name='publications',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensecertification',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talenttrack.Result', verbose_name='Proffessional Memberships / Certification type'),
        ),
        migrations.AddField(
            model_name='licensecertification',
            name='companybranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterprises.Enterprise', verbose_name='Issued By'),
        ),
        migrations.AddField(
            model_name='licensecertification',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.Region'),
        ),
        migrations.AddField(
            model_name='licensecertification',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenttrack.WorkExperience'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='talenttrack.Topic', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='emailremindvalidate',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailremindvalidate',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talenttrack.Result', verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='course',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterprises.Enterprise', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talenttrack.CourseType'),
        ),
        migrations.AddField(
            model_name='classmates',
            name='colleague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ClassMate'),
        ),
        migrations.AddField(
            model_name='classmates',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talenttrack.WorkExperience'),
        ),
        migrations.AddField(
            model_name='classmates',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talenttrack.Topic', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='awards',
            name='tag',
            field=models.ManyToManyField(to='db_flatten.SkillTag', verbose_name='Tag / Associated Skill'),
        ),
        migrations.AddField(
            model_name='awards',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievements',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workexperience',
            unique_together={('talent', 'hours_worked', 'date_from', 'date_to', 'course', 'topic', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='workcolleague',
            unique_together={('experience', 'colleague_name', 'date_captured')},
        ),
        migrations.AlterUniqueTogether(
            name='workcollaborator',
            unique_together={('experience', 'collaborator_name', 'date_captured')},
        ),
        migrations.AlterUniqueTogether(
            name='workclient',
            unique_together={('experience', 'client_name', 'date_captured')},
        ),
        migrations.AlterUniqueTogether(
            name='superior',
            unique_together={('experience', 'superior_name', 'date_captured')},
        ),
        migrations.AlterUniqueTogether(
            name='publications',
            unique_together={('talent', 'title', 'date_published')},
        ),
        migrations.AlterUniqueTogether(
            name='licensecertification',
            unique_together={('talent', 'cm_no')},
        ),
        migrations.AlterUniqueTogether(
            name='lecturer',
            unique_together={('education', 'lecturer', 'date_captured')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='classmates',
            unique_together={('education', 'colleague', 'date_captured')},
        ),
        migrations.AlterUniqueTogether(
            name='awards',
            unique_together={('talent', 'award', 'date_achieved')},
        ),
        migrations.AlterUniqueTogether(
            name='achievements',
            unique_together={('talent', 'achievement', 'date_achieved')},
        ),
    ]
