# Generated by Django 2.2 on 2021-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talenttrack', '0002_auto_20210627_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensecertification',
            name='cm_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Membership / Credential Number'),
        ),
    ]
