# Generated by Django 2.2 on 2021-09-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talenttrack', '0003_auto_20210707_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('F', 'Freelance'), ('C', 'Contract'), ('T', 'Consultant'), ('E', 'Employee'), ('O', 'FIFO')], default='F', max_length=1, null=True),
        ),
    ]
