from django.urls import path

from .import views

app_name = 'Profile'

urlpatterns = [
        path('', views.ProfileHome, name="ProfileHome"),
        path('view/', views.ProfileView, name="ProfileView"),
        path('edit/<slug:tlt>/', views.ProfileEditView, name="ProfileEdit"),
        path('background/<slug:tlt>/', views.ProfileBackgroundEditView, name="BackgroundEdit"),
        path('motivation/<slug:tlt>/', views.ProfileMotivationEditView, name="MotivationEdit"),
        path('email/<slug:tlt>/', views.EmailEditView, name='EmailEdit'),
        path('email/<slug:tlt>/<slug:eml>/', views.EmailStatusView, name='EmailStatus'),
        path('email/delete/<int:pk>/<slug:tlt>/', views.EmailDelete, name='EmailDelete'),
        path('address/physical/', views.PhysicalAddressView, name='PhysicalAddress'),
        path('address/postal/', views.PostalAddressView, name='PostalAddress'),
        path('phone/add/', views.PhoneNumberAdd, name='PhoneNumberAdd'),
        path('online/add/<slug:tlt>/', views.OnlineProfileAdd, name='OnlineProfileAdd'),
        path('online/delete/<int:pk>/<slug:tlt>/', views.OnlineDelete, name='OnlineDelete'),
        path('popup/add/', views.ProfileTypePopup, name="ProfileTypeAddPop"),
        path('popup/ajax/get_site_id/', views.get_SiteType_id, name="AJAX_GetSiteTypeID"),
        path('file/pftp/', views.FileUploadView, name='FileUploadView'),
        path('id/update/', views.IdentificationView, name='IdView'),
        path('popup/add/idtype/', views.IdTypePopup, name="IdTypeAddPop"),
        path('popup/ajax/get_IdType_id/', views.get_IdType_id, name="AJAX_GetIdTypeID"),
        path('passport/', views.PassportAddView, name='PassportAddView'),
        path('passport/<slug:psp>/<slug:tlt>/edit/', views.PassportEditView, name='PassportEditView'),
        path('language/<slug:tlt>/', views.LanguageAddView, name='LanguageAdd'),
        path('language/<slug:tlt>/<slug:lang>/', views.LanguageEditView, name='LanguageEdit'),
        path('language-del/<int:lang_id>/<slug:tlt>/', views.LanguageDeleteView, name='LanguageDelete'),
        path('popup/add/language/', views.LanguagePopup, name="LanguagePop"),
        path('popup/ajax/get_language_id/', views.get_language_id, name="AJAX_GetLanguageID"),
        path('passport/delete/<int:pk>/<slug:tlt>/', views.PassportDeleteView, name='PassportDelete'),
        path('phonenumber/delete/<int:pk>/', views.PhoneNumberDelete, name='PhoneDelete'),
        path('file/delete/<int:pk>/', views.FileDelete, name='FileDelete'),
        path('experience-review/', views.ConfirmView, name='Confirm'),
        path('lecturer-confirm/<int:pk>/', views.LecturerConfirmView, name='LecturerConfirm'),
        path('lecturer-reject/<int:pk>/', views.LecturerRejectView, name='LecturerReject'),
        path('lecturer-comment/<slug:lct>/', views.LecturerCommentView, name='LecturerComment'),
        path('lecturer-edit/<slug:lct>/', views.LecturerEditView, name='LecturerEdit'),
        path('lecturer-wrongperson/<int:pk>/', views.LecturerWrongPersonView, name='LecturerWrongPerson'),
        path('classmates-confirm/<int:pk>/', views.ClassMatesConfirmView, name='ClassMatesConfirm'),
        path('classmates-reject/<int:pk>/', views.ClassMatesRejectView, name='ClassMatesReject'),
        path('classmates-comment/<slug:cmt>/', views.ClassMatesCommentView, name='ClassMatesComment'),
        path('classmates-edit/<slug:cmt>/', views.ClassMatesEditView, name='ClassMatesEdit'),
        path('classmates-wrongperson/<int:pk>/', views.ClassMatesWrongPersonView, name='ClassMatesWrongPerson'),
        #Colleague Confirm
        path('colleague-confirm/<int:pk>/', views.ColleagueConfirmView, name='ColleagueConfirm'),
        path('colleague-reject/<int:pk>/', views.ColleagueRejectView, name='ColleagueReject'),
        path('colleague-wrongperson/<int:pk>/', views.ColleagueWrongPersonView, name='ColleagueWrongPerson'),
        path('colleague-comment/<slug:clg>/', views.ColleagueCommentView, name='ColleagueComment'),
        path('colleague-edit/<slug:clg>/', views.ColleagueEditView, name='ColleagueEdit'),
        #Superior Confirm
        path('superior-confirm/<int:pk>/', views.SuperiorConfirmView, name='SuperiorConfirm'),
        path('superior-reject/<int:pk>/', views.SuperiorRejectView, name='SuperiorReject'),
        path('superior-wrongperson/<int:pk>/', views.SuperiorWrongPersonView, name='SuperiorWrongPerson'),
        path('superior-comment/<slug:spr>/', views.SuperiorCommentView, name='SuperiorComment'),
        path('superior-edit/<slug:spr>/', views.SuperiorEditView, name='SuperiorEdit'),
        #Collaborator confirm
        path('collaborator-confirm/<int:pk>/', views.CollaboratorConfirmView, name='CollaboratorConfirm'),
        path('collaborator-reject/<int:pk>/', views.CollaboratorRejectView, name='CollaboratorReject'),
        path('collaborator-wrongperson/<int:pk>/', views.CollaboratorWrongPersonView, name='CollaboratorWrongPerson'),
        path('collaborator-comment/<slug:clb>/', views.CollaboratorCommentView, name='CollaboratorComment'),
        path('collaborator-edit/<slug:clb>/', views.CollaboratorEditView, name='CollaboratorEdit'),
        #Client Confirm
        path('client-confirm/<int:pk>/', views.ClientConfirmView, name='ClientConfirm'),
        path('client-reject/<int:pk>/', views.ClientRejectView, name='ClientReject'),
        path('client-wrongperson/<int:pk>/', views.ClientWrongPersonView, name='ClientWrongPerson'),
        path('client-comment/<slug:wkc>/', views.ClientCommentView, name='ClientComment'),
        path('client-edit/<slug:wkc>/', views.ClientEditView, name='ClientEdit'),
        #PreColleague Confirm
        path('precolleague-confirm/<int:pk>/', views.PreColleagueConfirmView, name='PreColleagueConfirm'),
        path('precolleague-reject/<int:pk>/', views.PreColleagueRejectView, name='PreColleagueReject'),
        path('precolleague-wrongperson/<int:pk>/', views.PreColleagueWrongPersonView, name='PreColleagueWrongPerson'),
        path('precolleague-comment/<slug:clg>/', views.PreColleagueCommentView, name='PreColleagueComment'),
        path('careerhistory/', views.BriefCareerHistoryView, name='History'),
        path('career-resign/<slug:bch>/<slug:tlt>/', views.ResignedView, name='Resigned'),
        path('int-remove/<slug:tlt>/', views.InterviewTltRemove, name='IntRemove'),
        path('int-accept/<int:int_id>/', views.InterviewAcceptView, name='IntAccept'),
        path('accept-int/<int:int_id>/', views.int_accept, name='IntAccept2'),
        path('int-decline/<int:int_id>/', views.InterviewDeclineView, name='IntDecline'),
        path('decline-int/<int:int_id>/', views.int_decline, name='IntDecline2'),
        path('int-complete/<int:int_id>/', views.InterviewTltComplete, name='IntComplete'),
        path('assignment-accept/<slug:slug>/', views.AssignmentAcceptView, name='AssignmentAccept'),
        path('assignment-decline/<slug:slug>/', views.AssignmentDeclineView, name='AssignmentDecline'),
        path('assignment-rfi/<slug:wit>/', views.AssignmentClarifyView, name='AssignmentClarify'),
        path('assignment-reassign/<slug:slug>/', views.AssignmentReAssign, name='AssignmentReassign'),
        #Talent Workshop
        path('workshop-tlt/', views.TltWorkshopView, name='WorkshopTlt'),
        path('tlt-mark-complete/<slug:wit>/', views.TltVacancyComplete, name="TltMarkComp"),
        path('rate-tlt/<slug:wit>/', views.TltUpdateStatusRate, name='TltRatePerformance'),
        path('rate-tlt-view/<slug:wit>/', views.TltRatingView, name='TltRateView'),
        #Employer Office
        path('workshop-emp/', views.EmpWorkshopView, name='WorkshopEmp'),
        path('rate-emp/<slug:wit>/', views.EmpUpdateStatusRate, name='EmpRatePerformance'),
        path('rate-emp-view/<slug:wit>/', views.EmpRatingView, name='EmpRateView'),
        path('emp-mark-complete/<slug:wit>/', views.EmpVacancyComplete, name="EmpMarkComp"),
        path('profile-viewed-report/', views.ProfileViewedReport, name='ProfileViewed'),
        # Help pages
        path('help/desktop/assignment-tracking/', views.HelpDesktopWorkshopView, name='HelpDesktopWorkshop'),
        path('help/desktop/information/', views.HelpDesktopInformationView, name='HelpDesktopInformation'),
        path('help/desktop/network/', views.HelpDesktopNetworkView, name='HelpDesktopNetwork'),
        path('help/desktop/workflow/', views.HelpDesktopWorkflowView, name='HelpDesktopWorkflow'),
        path('help/desktop/pending-interviews/', views.HelpDesktopPendingInterviewsView, name='HelpDesktopPendingInterviews'),
        path('help/desktop/assignments/', views.HelpDesktopAssignmentsView, name='HelpDesktopAssignments'),
        path('help/experience-review/lecturer/', views.HelpLecturerConfirmView, name='HelpConfirmLecturer'),
        path('help/experience-review/classmate/', views.HelpClassmateConfirmView, name='HelpConfirmClassmate'),
        path('help/experience-review/colleague/', views.HelpColleqagueConfirmView, name='HelpConfirmColleague'),
        path('help/experience-review/subordinate/', views.HelpSubordinateConfirmView, name='HelpConfirmSubordinate'),
        path('help/experience-review/co-worker/', views.HelpCoworkerConfirmView, name='HelpConfirmCoworker'),
        path('help/experience-review/coonsultant-contractor/', views.HelpContractorConfirmView, name='HelpConfirmContractor'),
        path('contact-detail/<slug:tlt>/<slug:vac>/', views.ContactDetailView, name="ContactDetail"),
        path('intro-MyWeXlog-introduction/', views.IntroIntroductionView, name="IntroIntroduction"),
        path('intro-capture-experience/', views.IntroCaptureExpreienceView, name="IntroCaptureExperience"),
        path('intro-capture-skills/', views.IntroCaptureSkillsView, name="IntroCaptureSkills"),
]
