# Generated by Django 2.2.4 on 2022-04-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0002_auto_20220319_0933'),
        ('socialaccount', '0002_auto_20210627_0913'),
    ]

    operations = [
    ]
