# Generated by Django 2.2 on 2021-06-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_corporate', '0001_initial'),
        ('talenttrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatestaff',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='talenttrack.Designation'),
        ),
    ]
