# Generated by Django 2.2 on 2021-06-27 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_corporate', '0002_corporatestaff_designation'),
        ('marketplace', '0002_auto_20210627_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatestaff',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corporatestaff',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.WorkLocation'),
        ),
        migrations.AlterUniqueTogether(
            name='orgstructure',
            unique_together={('corporate', 'level_name')},
        ),
    ]
