# Generated by Django 2.2.4 on 2022-04-09 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_corporate', '0002_corporatestaff_designation'),
        ('marketplace', '0002_auto_20220409_1906'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatestaff',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corporatestaff',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.WorkLocation'),
        ),
        migrations.AlterUniqueTogether(
            name='orgstructure',
            unique_together={('corporate', 'level_name')},
        ),
    ]
