# Generated by Django 2.2 on 2021-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20210627_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('X', 'Select'), ('B', 'Bug'), ('T', 'Comment'), ('S', 'Suggestion'), ('F', 'Request Feature'), ('C', 'Complaint'), ('M', 'Compliance'), ('M', 'I Got A Job')], default='X', max_length=1),
        ),
    ]
