# Generated by Django 2.2.4 on 2022-04-09 19:06

import WeXlog.storage_backends
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import marketplace.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidInterviewList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('P', 'Offer Pending'), ('I', 'Interview Pending'), ('S', 'Suitable'), ('N', 'Not Suitable'), ('D', 'Declined Offer'), ('A', 'Accepted Offer')], default='I', max_length=1)),
                ('comments_tlt', models.TextField(null=True)),
                ('tlt_response', models.CharField(choices=[('P', 'Interview Pending'), ('A', 'Accept Interview'), ('D', 'Decline Interview'), ('N', 'Not Interviewed'), ('Z', 'Offered Vacancy without Interview')], default='P', max_length=1)),
                ('tlt_reponded', models.DateTimeField(null=True)),
                ('tlt_intcomplete', models.BooleanField(default=False)),
                ('emp_intcomplete', models.BooleanField(default=False)),
                ('comments_emp', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidShortList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferance_rating', models.SmallIntegerField(default=0, null=True)),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Unsuccessful'), ('S', 'Short-listed'), ('D', 'Talent Declined'), ('I', 'Interview'), ('Z', 'Declined')], default='S', max_length=1, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeclineAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable', tinymce.models.HTMLField()),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Student'), (1, 'Beginner'), (2, 'Junior'), (3, 'Intermediate'), (4, 'Senior'), (5, 'Lead')], default=0)),
                ('min_hours', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='SkillRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalentAvailabillity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelance', models.BooleanField(default=False)),
                ('remote_freelance', models.BooleanField(default=False)),
                ('contract', models.BooleanField(default=False)),
                ('part_time', models.BooleanField(default=False)),
                ('permanent', models.BooleanField(default=False)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_1', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Employer Performance')),
                ('rate_2', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Payment Receipt')),
                ('rate_3', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Would you work for this employer again?')),
                ('payment_time', models.SmallIntegerField(choices=[(0, 'Select'), (1, 'Still Waiting!'), (2, 'Within 60 days or more'), (3, 'Within 30 days'), (4, 'Within 14 days'), (5, 'Within 5 days')], default=0, verbose_name='Days from invoice to receipt of payment')),
                ('date_rating', models.DateField(auto_now=True)),
                ('comment', tinymce.models.HTMLField(blank=True, null=True)),
                ('suggestions', tinymce.models.HTMLField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalentRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('ref_no', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='MyWeXlog Reference Number')),
                ('own_ref_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_deadline', models.DateField(blank=True, null=True, verbose_name='Work completed by')),
                ('permpos', models.BooleanField(blank=True, default=False, verbose_name='Permanent Position?')),
                ('hours_required', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('O', 'Once Off'), ('M', 'per Month'), ('D', 'per Day'), ('W', 'per Week'), ('P', 'Permanent Position'), ('S', 'Short Term Contract'), ('A', 'As and When Contract')], max_length=1)),
                ('rate_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rate_unit', models.CharField(choices=[('H', 'per Hour'), ('D', 'per Day'), ('M', 'per Month'), ('A', 'per Annum'), ('L', 'Lump Sum'), ('I', 'Market Related')], default='H', max_length=1)),
                ('bid_open', models.DateTimeField(auto_now_add=True, null=True)),
                ('bid_closes', models.DateTimeField(null=True, verbose_name='Applications Close')),
                ('offer_status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1)),
                ('scope', tinymce.models.HTMLField()),
                ('expectations', tinymce.models.HTMLField()),
                ('terms', models.FileField(blank=True, null=True, storage=WeXlog.storage_backends.PublicMediaStorage(), upload_to=marketplace.models.BidTerms, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('vac_wkfl', models.CharField(choices=[('S', 'Assigned'), ('A', 'Accepted'), ('I', 'Interviewing'), ('L', 'Short-listed'), ('P', 'Pending')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_1', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Talent Work Performance')),
                ('rate_2', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Completed on Time?')),
                ('rate_3', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Would you hire this person again?')),
                ('date_rating', models.DateField(auto_now=True)),
                ('comment', tinymce.models.HTMLField(blank=True, null=True)),
                ('personal_comment', tinymce.models.HTMLField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('suggestions', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('date_viewed', models.DateTimeField(auto_now_add=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('date_read', models.DateTimeField(auto_now_add=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('date_closed', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_unit', models.CharField(choices=[('H', 'per Hour'), ('D', 'per Day'), ('M', 'per Month'), ('A', 'per Annum'), ('L', 'Lump Sum'), ('I', 'Market Related')], default='H', max_length=1)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('bidreview', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Unsuccessful'), ('S', 'Short-listed'), ('D', 'Talent Declined'), ('I', 'Interview'), ('Z', 'Declined')], default='P', max_length=1, null=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('date_revised', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Remote freelance', 'Remote freelance'), ('Freelance', 'Freelance'), ('Consultant', 'Consultant'), ('Contractor', 'Contractor'), ('Employee', 'Employee'), ('FiFo', 'FiFo')], max_length=40, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkIssuedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlt_response', models.CharField(choices=[('P', 'Response Pending'), ('A', 'Accept Assignment'), ('D', 'Decline Assignment'), ('C', 'Clarification Requested')], default='P', max_length=1)),
                ('tlt_response_date', models.DateTimeField(null=True)),
                ('comments', models.TextField()),
                ('clarification_required', models.TextField(null=True)),
                ('rate_offered', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rate_unit', models.CharField(choices=[('H', 'per Hour'), ('D', 'per Day'), ('M', 'per Month'), ('A', 'per Annum'), ('L', 'Lump Sum'), ('I', 'Market Related')], default='H', max_length=1, null=True)),
                ('date_deliverable', models.DateTimeField(null=True)),
                ('date_begin', models.DateTimeField(null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_complete', models.DateTimeField(auto_now=True)),
                ('tlt_rated', models.BooleanField(default=False)),
                ('assignment_complete_tlt', models.BooleanField(default=False)),
                ('emp_rated', models.BooleanField(default=False)),
                ('assignment_complete_emp', models.BooleanField(default=False)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.Currency')),
            ],
        ),
    ]
