# Generated by Django 2.2 on 2021-06-29 17:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20210627_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverables',
            name='deliverable',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='talentrate',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentrate',
            name='suggestions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentrequired',
            name='expectations',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='talentrequired',
            name='scope',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='vacancyrate',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyrate',
            name='personal_comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyrate',
            name='suggestions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
