# Generated by Django 2.2 on 2022-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20220319_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentrequired',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
