# Generated by Django 2.2.4 on 2021-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20210629_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentrequired',
            name='hours_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentrequired',
            name='rate_offered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='talentrequired',
            name='rate_unit',
            field=models.CharField(choices=[('H', 'per Hour'), ('D', 'per Day'), ('M', 'per Month'), ('A', 'per Annum'), ('L', 'Lump Sum')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='talentrequired',
            name='unit',
            field=models.CharField(choices=[('O', 'Once Off'), ('M', 'per Month'), ('D', 'per Day'), ('W', 'per Week'), ('P', 'Permanent Position'), ('S', 'Short Term Contract'), ('A', 'As and When Contract')], max_length=1),
        ),
        migrations.AlterField(
            model_name='workbid',
            name='rate_unit',
            field=models.CharField(choices=[('H', 'per Hour'), ('D', 'per Day'), ('M', 'per Month'), ('A', 'per Annum'), ('L', 'Lump Sum')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='workissuedto',
            name='rate_unit',
            field=models.CharField(choices=[('H', 'per Hour'), ('D', 'per Day'), ('M', 'per Month'), ('A', 'per Annum'), ('L', 'Lump Sum')], default='H', max_length=1, null=True),
        ),
    ]
