# Generated by Django 2.2.4 on 2021-10-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20211003_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentrequired',
            name='permpos',
            field=models.BooleanField(blank=True, default=False, verbose_name='Permanent Position?'),
        ),
    ]
