# Generated by Django 2.2.4 on 2022-04-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterprisePassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_score', models.DateField(auto_now_add=True)),
                ('payment_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('payment_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('cooperation_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('cooperation_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('treatment_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('treatment_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('information_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('information_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('engagement_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('engagement_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('accuracy_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('accuracy_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
            ],
        ),
        migrations.CreateModel(
            name='TalentPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_score', models.DateField(auto_now_add=True)),
                ('q1_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q1_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q2_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q2_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q3_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q3_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q4_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q4_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q5_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q5_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q6_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q6_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q7_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q7_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q8_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q8_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q9_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q9_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q10_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q10_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q12_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q12_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q13_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q13_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q14_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q14_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
                ('q15_text', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('q15_score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Score')),
            ],
        ),
    ]
