from django.urls import path

from . import views

app_name = 'MarketPlace'


urlpatterns = [
    path('entrance/', views.MarketHome, name='Entrance'),
    path('vacancy-viewed-updated/', views.VacancyViewedJsonView, name='VacancyViewedJson'),
    path('close-vacancy/<int:tlt>/<int:vac>/', views.CloseVacancyAvailableCard, name='CloseVacancy'),
    path('minimise-vacancy/<int:tlt>/<int:vac>/', views.MinimiseVacancyAvailableCard, name='MinimiseVacancy'),
    path('maximise-vacancy/<int:tlt>/<int:vac>/', views.MaximiseVacancyAvailableCard, name='MaximiseVacancy'),

    path('vacancy/', views.VacancyView, name='Vacancy'),
    path('popup/worklocation/add/', views.WorkLocationAddPopup, name="WorkLocationAddPop"),
    path('popup/ajax/get_worklocation_id/', views.get_worklocation_id, name="AJAX_GetWorklocationID"),
    path('vacancy-deliverables/<slug:vac>/', views.DeliverablesAddView, name='Deliverables'),
    path('vacancy-deliverable/<slug:vac>/', views.DeliverablesAdd2View, name='Deliverables2'),
    path('vacancy-skills/<slug:vac>/', views.VacancySkillsAddView, name='Skills'),
    path('vacancy-skilla/<slug:vac>/', views.VacancySkillsAdd2View, name='Skillsa'),
    path('popup/skilllevel/add/', views.SkillLevelAddPopup, name="SkillLevelAddPop"),
    path('popup/ajax/get_skilllevel_id/', views.get_skilllevel_id, name="AJAX_GetSkillLevelID"),
    path('vacancy-edit/<slug:vac>/', views.VacancyEditView, name="VacancyEdit"),
    path('vacancy-edit-deliverables/<slug:vac>/', views.DeliverablesEditView, name='DeliverablesEdit'),
    path('vacancy-delete-deliverables/<int:pk>/', views.DeliverableDeleteView, name='DeliverablesDelete'),
    path('vacancy-delete-certificate/<slug:vac>/<str:cert>/', views.CertificateDeleteView, name='CertificateDelete'),
    path('vacancy-delete-skill/<int:id>/', views.SkillDeleteView, name='SkillDelete'),

    path('availability/', views.TalentAvailabillityView, name='Availabillity'),
    path('v-detail/<slug:vac>/', views.VacancyDetailView, name='VacancyDetail'),
    path('public/vacancy/<slug:vac>/', views.VacancyDetailPublicView, name='VacancyDetailPublic'),
    path('vp-detail/<slug:vac>/', views.VacancyDetailView_Profile, name='VacancyDetail_Profile'),
    path('apply/<slug:vac>/', views.WorkBidView, name='WorkBid'),
    path('history/', views.ApplicationHistoryView, name='History'),
    path('postview/<slug:vac>/', views.VacancyPostView, name='VacancyPost'),
    path('vac-close/<slug:vac>/', views.VacancyCloseSwitch, name='VacClose'),

    path('vac-assign/<slug:vac>/<slug:tlt>/', views.TalentAssign, name='VacAssign'),
    path('vac-assign-edit/<slug:wit>/', views.talent_assign_edit, name='VacAssignEdit'),
    path('suitable-vac-assign/<slug:vac>/<slug:tlt>/', views.SuitableTalentAssign, name='SuitableVacAssign'),


    path('all-vac/', views.AllPostedVacanciesView, name="AllPostedVac"),
    path('all-vac/open/', views.AllPostedVacanciesOpenView, name='AllPostedVacOpen'),
    path('all-vac/closed/', views.AllPostedVacanciesClosedView, name='AllPostedVacClosed'),
    path('availabillity-remove/<int:avl_id>/', views.AvailabillityRemoveView, name='NotAvailable'),

    path('reject-bid-from-list/<slug:vac>/<slug:tlt>/', views.AppliedListRejectedView, name='RejectBidFromAppliedList'),
    #ShortList URLs
    path('shortlist-review/<slug:vac>/', views.ShortListView, name='ShortListView'),
    path('shortlist/<slug:vac>/<slug:tlt>/', views.AddToShortListView, name='ShortList'),
    path('full-list/shortlist/<slug:vac>/<slug:tlt>/', views.AddToShortListFullListView, name='FullListShortList'),
    path('applicants/shortlist/<slug:vac>/<slug:tlt>/', views.AddToShortListApplicantsView, name='ApplicantsShortList'),
    path('applicants/bid-shortlist/<slug:vac>/<slug:tlt>/', views.AddShortListApplicantsView, name='ApplicantsBidShortList'),
    path('vac-decline/<slug:vac>/<slug:tlt>/', views.TalentDecline, name='VacDecline'),
    path('sl-notsuitable/<slug:bil>/<slug:tlt>/', views.EmpSlDeclineComment, name='SlNotSuitable'),

    #Interview URLs
    #path('interviewlist/<slug:vac>/<slug:tlt>/', views.AddToInterviewListView, name='InterviewList'),
    path('interviewlist/<slug:vac>/', views.InterviewListView, name='InterviewList'),
    path('pending-interviewlist/<slug:vac>/', views.PendingInterviewListView, name='PendingInterviewList'),
    path('suitable-interviewlist/<slug:vac>/', views.SuitableInterviewListView, name='SuitableInterviewList'),
    path('unsuitable-interviewlist/<slug:vac>/', views.UnsuitableInterviewListView, name='UnsuitableInterviewList'),
    path('bid-rejected-list/<slug:vac>/', views.BidRejectedListView, name='BidRejectedList'),
    path('declined-invitation-interviewlist/<slug:vac>/', views.DeclinedInvInterviewListView, name='DeclinedInvInterviewList'),
    path('declined-assignment-interviewlist/<slug:vac>/', views.DeclinedAssignmentInterviewListView, name='DeclinedAssignmentInterviewList'),
    path('vac-interview/<slug:vac>/<slug:tlt>/', views.AddToInterviewListView, name='VacInterview'),
    path('int-decline/<int:int_id>/', views.InterviewDeclineView, name='InterviewDecline'),
        #InterviewList Views
    path('suitable/<slug:vac>/<slug:tlt>/', views.InterviewSuitable, name='Suitable'),
    path('suitable-dsh/<slug:vac>/<slug:tlt>/', views.dash_int_suitable, name='DashSuitable'),
    path('unsuitable-suitable/<slug:vac>/<slug:tlt>/', views.UnsuitableInterviewSuitable, name='UnsuitableSuitable'),
    path('pending-suitable/<slug:vac>/<slug:tlt>/', views.PendingInterviewSuitable, name='PendingSuitable'),
    path('not-suitable/<slug:vac>/<slug:tlt>/', views.InterviewNotSuitable, name='NotSuitable'),
    path('dash-not-suitable/<slug:vac>/<slug:tlt>/', views.dash_notsuitable, name='DashNotSuitable'),
    path('pending-not-suitable/<slug:vac>/<slug:tlt>/', views.PendingInterviewNotSuitable, name='PendingNotSuitable'),
    path('suitable-not-suitable/<slug:vac>/<slug:tlt>/', views.SuitableInterviewNotSuitable, name='SuitableNotSuitable'),
        #InterView History
    path('interview-history/<slug:tlt>/', views.TalentInterviewHistoryView, name="TalentInterviewHistory"),
    path('interview-historye/<slug:tlt>/', views.EmployerInterviewHistoryView, name="EmployerInterviewHistory"),
        #tlt int close URLs
    path('tlt-int-close/<slug:bil>/<slug:tlt>/', views.TltInterviewClose, name='TalentIntClose'),
    path('tlt-int-detail/<slug:bil>/<slug:tlt>/', views.TltIntFullDetail, name='TalentIntDetail'),
    path('tlt-int-comment/<slug:bil>/<slug:tlt>/', views.TltIntCommentView, name='TalentIntComment'),
        #emp int close URLs
    path('emp-int-close/<slug:bil>/<slug:tlt>/', views.EmpInterviewClose, name='EmployerIntClose'),
    path('emp-dash-close/<slug:bil>/<slug:tlt>/', views.emp_dashint_close, name='Emp_DashIntClose'),
    path('emp-int-detail/vac/<slug:bil>/<slug:tlt>/', views.EmpIntFullDetail, name='EmployerIntDetail'),
    path('emp-int-detail/<slug:vac>/', views.EmpIntDetailVacancy, name='VacancyIntDetail'),
    path('emp-int-comment/<slug:bil>/<slug:tlt>/', views.EmpIntCommentView, name='VacancyIntComment'),

    path('rfi-respond/<slug:wit>/', views.TalentRFIView, name='RFIView'),
    path('vacancy-search/', views.VacancySearch, name="VacSearch"),
    path('vacancy/vacancies-full-list/', views.VacanciesListView, name="VacanciesList"),
    path('vacancy/talent-suited-to-vacancy/<slug:vac>/', views.TalentSuitedVacancyListView, name='TalentSuitedToVacancy'),
    path('vacancy/applicants-for-vacancy/<slug:vac>/', views.ApplicantsForVacancyListView, name='ApplicantsForVacancy'),

    path('vacancy/suited/expanded-list/', views.ExpandVacanciesSuitedView, name='VacanciesExpand'),
    path('vacancy/suited/fl-expanded-list/', views.ExpandVacanciesSuitedFLView, name='VacanciesFLExpand'),

    path('vacancy/applicants/expanded-list/<slug:vac>/', views.ExpandApplicantsView, name='AppExpand'),
    path('vacancy/applicants/fl-expanded-list/<slug:vac>/', views.ExpandApplicantsFLView, name='AppFLExpand'),
    path('vacancy/talent-suited/expanded-list/<slug:vac>/', views.ExpandTalentSuitedView, name='SuitedExpand'),
    path('vacancy/talent-suited/fl-expanded-list/<slug:vac>/', views.ExpandTalentSuitedFLView, name='SuitedFLExpand'),
    path('vacancy/short-list/expanded-list/', views.ExpandShortListView, name='ShortlistExpand'),
    path('vacancy-dashboard/pending-interviews/expanded-list/<slug:vac>/', views.ExpandPendingInterviewsView, name='PendingInterviewsExpand'),
    path('vacancy-dashboard/pending-interviews/fl-expanded-list/<slug:vac>/', views.ExpandPendingInterviewsFLView, name='PendingInterviewsFLExpand'),
    path('vacancy-dashboard/suitable-applicants/expanded-list/<slug:vac>/', views.ExpandSuitableApplicantsView, name='SuitableApplicanctExpand'),
    path('vacancy-dashboard/suitable-applicants/fl-expanded-list/<slug:vac>/', views.ExpandSuitableApplicantsFLView, name='SuitableApplicanctFLExpand'),
    path('vacancy-dashboard/unsuitable-applicants/expanded-list/<slug:vac>/', views.ExpandUnSuitableApplicantsView, name='UnSuitableApplicanctExpand'),
    path('vacancy-dashboard/unsuitable-applicants/fl-expanded-list/<slug:vac>/', views.ExpandUnSuitableApplicantsFLView, name='UnSuitableApplicanctFLExpand'),
    path('vacancy-dashboard/rejected-applicants/expanded-list/<slug:vac>/', views.ExpandRejectedApplicantsView, name='RejectedApplicanctExpand'),
    path('vacancy-dashboard/rejected-applicants/fl-expanded-list/<slug:vac>/', views.ExpandRejectedApplicantsFLView, name='RejectedApplicanctFLExpand'),
    path('vacancy/application-history-full-list/', views.RolesAppliedForApplicationHistoryView, name='RolesAppliedForFullList'),
    path('vacancy/shortlisted-history-full-list/', views.RolesShortlistedForApplicationHistoryView, name='RolesShortlistedFullList'),
    path('vacancy/open-interviews-full-list/', views.RolesOpenInterviewsApplicationHistoryView, name='RolesOpenInterviewsFullList'),
    path('vacancy/unsuccessful-applications-history-full-list/', views.UnsuccessfulApplicationHistoryView, name='UnsuccessfulApplicationsFullList'),
    path('vacancy/successful-applications-history-full-list/', views.SuccessfulApplicationHistoryView, name='SuccessfulApplicationsFullList'),
    path('vacancy/pending-shortlisted-application-history-full-list/', views.RolesAppliedForShortlistedApplicationHistoryView, name='RolesAppliedForShortlistedFullList'),
    path('vacancy/pending-interviews-application-history-full-list/', views.RolesAppliedForInterviewsApplicationHistoryView, name='RolesAppliedForInterviewsFullList'),
    path('vacancy/successful-application-history-full-list/', views.RolesAppliedForSuccessfulApplicationHistoryView, name='RolesAppliedForSuccessfulFullList'),
    path('vacancy/unsuccessful-application-history-full-list/', views.RolesAppliedForUnsuccessfulApplicationHistoryView, name='RolesAppliedForUnsuccessfulFullList'),

    path('jooble-feed/', views.jooble_feed, name="jooble-feed"),
    path('indeed-feed/', views.indeed_feed, name="indeed-feed"),

    #Help urls
    path('help/Experience-level/', views.ExperienceLevelHelpView, name="HelpExperienceLevel"),
    path('help/Work-Configeration/', views.WorkConfigerationHelpView, name="HelpWorkCOnfigeration"),
    path('help/vacancy-capture/', views.HelpPostVacancyView, name='HelpPostVacancy'),
    path('help/vacancies-suited-for-me-summary/', views.HelpVacancySuitedSummaryView, name='HelpVacanciesSuitedForMeSummary'),
    path('help/vacancies-suited-for-me-full-list/', views.HelpVacancySuitedFullView, name='HelpVacanciesSuitedForMeFull'),
    path('help/vacancies-advertised-open-summary/', views.HelpVacancyAdvertisedOpenSummaryView, name='HelpVacanciesAdvertisedOpenSummary'),
    path('help/vacancies-advertised-open-all/', views.HelpVacancyAdvertisedOpenAllView, name='HelpVacanciesAdvertisedOpenAll'),
    path('help/vacancies-advertised-full-list/', views.HelpVacancyAdvertisedFullView, name='HelpVacanciesAdvertisedFull'),
    path('help/vacancies-advertised-closed-all/', views.HelpVacancyAdvertisedClosedAllView, name='HelpVacanciesAdvertisedClosedAll'),
    path('help/vacancies-advertised-closed-summary/', views.HelpVacancyAdvertisedClosedSummaryView, name='HelpVacanciesAdvertisedClosedSummary'),
    path('help/my-availability/', views.HelpAvailabilityView, name='HelpAvailability'),
    path('help/application-history/roles-applied-for-summary/', views.HelpApplicationHistoryRolesAppliedForSummaryView, name='HelpRolesAppliedForSummary'),
    path('help/application-history/roles-applied-for-full-list/', views.HelpApplicationHistoryRolesAppliedForFullView, name='HelpRolesAppliedForFull'),
    path('help/application-history/roles-shortlisted-for-summary/', views.HelpApplicationHistoryRolesShortlistedForSummaryView, name='HelpRolesShortlistedForSummary'),
    path('help/application-history/roles-shortlisted-for-full-list/', views.HelpApplicationHistoryRolesShortlistedForFullView, name='HelpRolesShortlistedForFull'),
    path('help/application-history/unsuccessful-applications-summary/', views.HelpApplicationHistoryUnsuccessfulApplicationsSummaryView, name='HelpUnseccessfulApplicationsSummary'),
    path('help/application-history/unsuccessful-applications-full-list/', views.HelpApplicationHistoryUnsuccessfulApplicationsFullView, name='HelpUnseccessfulApplicationsFull'),
    path('help/application-history/successful-applications-summary/', views.HelpApplicationHistorySuccessfulApplicationsSummaryView, name='HelpSeccessfulApplicationsSummary'),
    path('help/application-history/successful-applications-full-list/', views.HelpApplicationHistorySuccessfulApplicationsFullView, name='HelpSeccessfulApplicationsFull'),
    path('help/vacancy-review/', views.HelpVacancyPostView, name='HelpVacancyPost'),
    path('help/vacancy-review/talent-suited-to-vacancy/', views.HelpTalentSuitedToVacancyView, name='HelpTalentSuitedVacancy'),
    path('help/vacancy-review/talent-suited-to-vacancy-full-list/', views.HelpTalentSuitedToVacancyFullView, name='HelpTalentSuitedVacancyFull'),
    path('help/vacancy-review/applicants-for-vacancy/', views.HelpApplicantsView, name='HelpApplicantsVacancy'),
    path('help/vacancy-review/applicants-for-vacancy-full-list/', views.HelpApplicantsFullView, name='HelpApplicantsVacancyFull'),
    path('help/interview-history-all/', views.HelpInterviewHistoryAllView, name='HelpInterviewHistoryAll'),
    path('help/interview-history-employer-all/', views.HelpEmployerInterviewHistoryAllView, name='HelpInterviewHistoryEmployerAll'),
    path('help/interview-detail/', views.HelpInterviewDetailView, name='HelpInterviewDetail'),
    path('help/deliverable/', views.HelpDeliverable2View, name='HelpDeliverable2'),
    path('help/deliverables/', views.HelpDeliverablesView, name='HelpDeliverables'),


]
