# Generated by Django 2.2 on 2022-03-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.SmallIntegerField(choices=[(0, 'Light'), (1, 'Medium'), (2, 'Heavy')], default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('expiry', models.DateField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=9)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.Enterprise')),
                ('companybranch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.Branch')),
            ],
            options={
                'verbose_name_plural': 'Corporate HR',
            },
        ),
    ]
