# Generated by Django 2.2 on 2022-03-19 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpersonaldetails',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.City'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprises.Enterprise', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='companybranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprises.Branch', verbose_name='Branch Managing the Project'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterprises.Industry'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='projectpersonaldetails',
            unique_together={('talent', 'project', 'company', 'companybranch')},
        ),
        migrations.AlterUniqueTogether(
            name='projectdata',
            unique_together={('name', 'companybranch')},
        ),
    ]
