# Generated by Django 2.2 on 2023-04-09 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('db_flatten', '0001_initial'),
        ('enterprises', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20220409_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPersonalDetailsTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=50, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('task_status', models.IntegerField(choices=[(0, 'Due'), (1, 'Pending'), (2, 'Current'), (3, 'Complete')], default=2)),
                ('date_due', models.DateTimeField(blank=True, null=True, verbose_name='due on')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='completed on')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client', to='enterprises.Branch')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Company', to='enterprises.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='projectdata',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Overall project description'),
        ),
        migrations.AddField(
            model_name='projectpersonaldetails',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprises.Enterprise', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='companybranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprises.Branch', verbose_name='Branch Working for on the Project'),
        ),
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectData'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectTaskBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_unit', models.CharField(choices=[('H', 'per Hour'), ('D', 'per Day'), ('M', 'per Month'), ('L', 'Lump Sum')], default='H', max_length=1)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Currency')),
                ('ppdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPersonalDetailsTask', verbose_name='Task')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectpersonaldetailstask',
            name='ppd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPersonalDetails'),
        ),
        migrations.AddField(
            model_name='projectpersonaldetailstask',
            name='skills',
            field=models.ManyToManyField(related_name='task_skills', to='db_flatten.SkillTag'),
        ),
        migrations.AddField(
            model_name='projectpersonaldetailstask',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
