# Generated by Django 2.2 on 2021-06-29 17:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210627_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
