# Generated by Django 2.2 on 2021-09-01 16:07

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210629_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.Enterprise', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='companybranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.Branch', verbose_name='Branch Working for on the Project'),
        ),
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Personal responsibilities description'),
        ),
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ProjectData'),
        ),
    ]
