# Generated by Django 2.2 on 2021-09-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210901_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.Enterprise', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='companybranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.Branch', verbose_name='Branch Working for on the Project'),
        ),
        migrations.AlterField(
            model_name='projectpersonaldetails',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ProjectData'),
        ),
    ]
