# Generated by Django 2.2 on 2022-03-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0001_initial'),
        ('talenttrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talenttrack.WorkExperience'),
        ),
    ]
