# Generated by Django 2.2 on 2021-06-29 17:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_invitation_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
