# Generated by Django 2.2.4 on 2022-04-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_invitation_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='slug',
            field=models.SlugField(max_length=9, null=True, unique=True),
        ),
    ]
