# Generated by Django 2.2.4 on 2021-10-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20210629_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='companybranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.Branch', verbose_name='Who did they work for at the time'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talenttrack.WorkExperience'),
        ),
    ]
