# Generated by Django 2.2.4 on 2021-10-28 18:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=250, verbose_name='Region (Optional)')),
                ('skill1', models.CharField(max_length=150, verbose_name='Skill 1')),
                ('skill2', models.CharField(blank=True, max_length=150, verbose_name='Skill 2 (Optional)')),
                ('skill3', models.CharField(blank=True, max_length=150, verbose_name='Skill 3 (Optional)')),
                ('skill4', models.CharField(blank=True, max_length=150, verbose_name='Skill 4 (Optional)')),
            ],
        ),
    ]
