# Generated by Django 2.2.4 on 2021-10-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillFilter',
        ),
    ]
