# Generated by Django 2.2 on 2021-06-27 09:13

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(max_length=80, verbose_name='Region / State / etc.')),
            ],
            options={
                'ordering': ['region'],
                'unique_together': {('country', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('currency_name', models.CharField(max_length=150, verbose_name='Currency')),
                ('currency_abv', models.CharField(max_length=3, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'unique_together': {('country', 'currency_name')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80, verbose_name='City, Town, or Place')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Region')),
            ],
            options={
                'ordering': ['city'],
                'unique_together': {('region', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=80)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.City')),
            ],
            options={
                'ordering': ['suburb'],
                'unique_together': {('suburb', 'city')},
            },
        ),
    ]
