# Generated by Django 2.2 on 2022-03-19 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booklist', '0001_initial'),
        ('db_flatten', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readby',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readby',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklist.Format', verbose_name='Book Format'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='author',
            field=models.ManyToManyField(to='booklist.Author'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='genre',
            field=models.ManyToManyField(to='booklist.Genre'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklist.Publisher'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='tag',
            field=models.ManyToManyField(to='db_flatten.SkillTag', verbose_name='Tag / Associated Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='readby',
            unique_together={('talent', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='booklist',
            unique_together={('title', 'publisher')},
        ),
    ]
