# Generated by Django 2.2 on 2021-09-11 16:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_auto_20210901_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='readby',
            name='review',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
